---
- name: obtain and install composer
  sudo: true
  shell: |
      command -v composer > /dev/null
      if [ $? -ne 0 ]; then
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
      fi
